### PR TITLE
package-lock-json

### PR DESCRIPTION
**Pull request by Rakesh678219**

### CODE REVIEW

**Comment by divshekhar** [comment]
Hello @Rakesh678219 , Please provide a description for the pull request.

**Comment by divshekhar** [comment]
Hello @Rakesh678219 , It seems you are pushing to the wrong origin, please correct it. Closing the PR.

**Comment by Rakesh678219** [comment]
sorry i just want to use the template u created , i just forked and
continue to work one

**Comment by Rakesh678219** [comment]
will there be any problem for me ??

**Comment by divshekhar** [comment]
There is no problem, you just have to correct the origin of your fork, and you are good to go again! Let me know if you find any bugs or issues in the template.

**Comment by Rakesh678219** [comment]
Awesome, thank you so much!

**Comment by Rakesh678219** [comment]
Hi I am not able to deploy my site in netlify , is something wrong in the
build command u added in package.json could u check once please

**Pull request closed without merging**
